#!/bin/sh
# Code generated by craft; DO NOT EDIT.

case $BINARY_NAME in
    cron-refresh) /app/cron-refresh;;
    worker-appli) /app/worker-appli;;
    *) echo "invalid binary '$BINARY_NAME'" && exit 1;;
esac