# Code generated by craft; DO NOT EDIT.

.PHONY: build
build:
	@hugo --gc --minify --destination public

.PHONY: serve
serve:
	@hugo server --disableFastRender

.PHONY: production
production:
	@netlify dev -c "make serve" \
		--target-port 1313 --port 8888 
		--dir public 
		--framework hugo 
		--context production