// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "craft",
    "version": "0.1.0"
  },
  "basePath": "/api",
  "paths": {
    "/unsecured/ping": {
      "get": {
        "description": "checks API health and retrieves ping result",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Monitoring"
        ],
        "summary": "checks API health and retrieves ping result",
        "operationId": "unsecuredPing",
        "responses": {
          "200": {
            "description": "success response returning ping results",
            "schema": {
              "$ref": "#/definitions/UnsecuredPing"
            }
          },
          "default": {
            "description": "default error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/unsecured/test-tag": {
      "get": {
        "description": "tests that a tag operation is generated like it would be expected",
        "produces": [
          "application/json"
        ],
        "tags": [
          "TestTag"
        ],
        "summary": "tests that a tag operation is generated like it would be expected",
        "operationId": "testTag",
        "responses": {
          "204": {
            "description": "success response test tag result"
          },
          "default": {
            "description": "default error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "error code",
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "description": "error message",
          "type": "string"
        }
      }
    },
    "UnsecuredPing": {
      "type": "object",
      "properties": {
        "status": {
          "description": "ping status",
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "monitoring endpoints",
      "name": "Monitoring"
    },
    {
      "description": "a tag that should appear in bytes comparison",
      "name": "TestTag"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "craft",
    "version": "0.1.0"
  },
  "basePath": "/api",
  "paths": {
    "/unsecured/ping": {
      "get": {
        "description": "checks API health and retrieves ping result",
        "produces": [
          "application/json"
        ],
        "tags": [
          "Monitoring"
        ],
        "summary": "checks API health and retrieves ping result",
        "operationId": "unsecuredPing",
        "responses": {
          "200": {
            "description": "success response returning ping results",
            "schema": {
              "$ref": "#/definitions/UnsecuredPing"
            }
          },
          "default": {
            "description": "default error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/unsecured/test-tag": {
      "get": {
        "description": "tests that a tag operation is generated like it would be expected",
        "produces": [
          "application/json"
        ],
        "tags": [
          "TestTag"
        ],
        "summary": "tests that a tag operation is generated like it would be expected",
        "operationId": "testTag",
        "responses": {
          "204": {
            "description": "success response test tag result"
          },
          "default": {
            "description": "default error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "error code",
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "description": "error message",
          "type": "string"
        }
      }
    },
    "UnsecuredPing": {
      "type": "object",
      "properties": {
        "status": {
          "description": "ping status",
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "monitoring endpoints",
      "name": "Monitoring"
    },
    {
      "description": "a tag that should appear in bytes comparison",
      "name": "TestTag"
    }
  ]
}`))
}
