# Code generated by craft; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

.PHONY: build
build:
	@hugo --gc --minify --destination dist --logLevel debug

.PHONY: serve
serve:
	@hugo server --disableFastRender --destination dist --logLevel debug

.PHONY: production
production:
	@netlify dev -c "make serve" \
		--target-port 1313 --port 8888
		--dir dist
		--framework hugo
		--context production
