package handler

import (
	"os"
	"strings"
)

// generated is the string for generated files.
const generated = "Code generated by craft; DO NOT EDIT."

// IsGenerated returns truthy if input destination is a generated file.
func IsGenerated(dest string) bool {
	// retrieve file content, if there's an error, generation to make
	content, err := os.ReadFile(dest)
	if err != nil {
		return true
	}

	// special case (shouldn't happen) where the destination has been replaced with an empty file
	if len(content) == 0 {
		return true
	}
	lines := strings.Split(string(content), "\n")

	// check first line for generated regexp
	if len(lines) >= 1 && strings.Contains(lines[0], generated) {
		return true
	}

	// check second line for generated regexp
	if len(lines) >= 2 && strings.Contains(lines[1], generated) {
		return true
	}
	return false
}
