// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// APIBuilder is an alias of API to build API with builder-pattern.
type APIBuilder models.API

// NewAPIBuilder creates a new APIBuilder.
func NewAPIBuilder() *APIBuilder {
	return &APIBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *APIBuilder) Copy() *APIBuilder {
	c := *b
	return &c
}

// Build returns built API.
func (b *APIBuilder) Build() *models.API {
	c := (models.API)(*b)
	return &c
}

// SetOpenAPIVersion sets API's OpenAPIVersion.
func (b *APIBuilder) SetOpenAPIVersion(openAPIVersion string) *APIBuilder {
	b.OpenAPIVersion = &openAPIVersion
	return b
}
