// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// APIBuilder represents API's builder.
type APIBuilder struct {
	build models.API
}

// NewAPIBuilder creates a new APIBuilder.
func NewAPIBuilder() *APIBuilder {
	return &APIBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *APIBuilder) Copy() *APIBuilder {
	return &APIBuilder{b.build}
}

// Build returns built API.
func (b *APIBuilder) Build() *models.API {
	result := b.build
	return &result
}

// SetOpenAPIVersion sets API's OpenAPIVersion.
func (b *APIBuilder) SetOpenAPIVersion(openAPIVersion string) *APIBuilder {
	b.build.OpenAPIVersion = &openAPIVersion
	return b
}
