// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// CIBuilder is an alias of CI to build CI with builder-pattern.
type CIBuilder models.CI

// NewCIBuilder creates a new CIBuilder.
func NewCIBuilder() *CIBuilder {
	return &CIBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *CIBuilder) Copy() *CIBuilder {
	c := *b
	return &c
}

// Build returns built CI.
func (b *CIBuilder) Build() *models.CI {
	c := (models.CI)(*b)
	return &c
}

// SetName sets CI's Name.
func (b *CIBuilder) SetName(name string) *CIBuilder {
	b.Name = name
	return b
}

// SetOptions sets CI's Options.
func (b *CIBuilder) SetOptions(options ...string) *CIBuilder {
	b.Options = append(b.Options, options...)
	return b
}
