// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// CraftConfigBuilder represents CraftConfig's builder.
type CraftConfigBuilder struct {
	build models.CraftConfig
}

// NewCraftConfigBuilder creates a new CraftConfigBuilder.
func NewCraftConfigBuilder() *CraftConfigBuilder {
	return &CraftConfigBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *CraftConfigBuilder) Copy() *CraftConfigBuilder {
	return &CraftConfigBuilder{b.build}
}

// Build returns built CraftConfig.
func (b *CraftConfigBuilder) Build() *models.CraftConfig {
	result := b.build
	return &result
}

// CI sets CraftConfig's CI.
func (b *CraftConfigBuilder) CI(ci models.CI) *CraftConfigBuilder {
	b.build.CI = &ci
	return b
}

// Description sets CraftConfig's Description.
func (b *CraftConfigBuilder) Description(description string) *CraftConfigBuilder {
	b.build.Description = &description
	return b
}

// Docker sets CraftConfig's Docker.
func (b *CraftConfigBuilder) Docker(docker models.Docker) *CraftConfigBuilder {
	b.build.Docker = &docker
	return b
}

// License sets CraftConfig's License.
func (b *CraftConfigBuilder) License(license string) *CraftConfigBuilder {
	b.build.License = &license
	return b
}

// Maintainers sets CraftConfig's Maintainers.
func (b *CraftConfigBuilder) Maintainers(maintainers ...models.Maintainer) *CraftConfigBuilder {
	b.build.Maintainers = append(b.build.Maintainers, maintainers...)
	return b
}

// NoChart sets CraftConfig's NoChart.
func (b *CraftConfigBuilder) NoChart(noChart bool) *CraftConfigBuilder {
	b.build.NoChart = noChart
	return b
}

// NoGoreleaser sets CraftConfig's NoGoreleaser.
func (b *CraftConfigBuilder) NoGoreleaser(noGoreleaser bool) *CraftConfigBuilder {
	b.build.NoGoreleaser = noGoreleaser
	return b
}

// NoMakefile sets CraftConfig's NoMakefile.
func (b *CraftConfigBuilder) NoMakefile(noMakefile bool) *CraftConfigBuilder {
	b.build.NoMakefile = noMakefile
	return b
}

// Platform sets CraftConfig's Platform.
func (b *CraftConfigBuilder) Platform(platform string) *CraftConfigBuilder {
	b.build.Platform = platform
	return b
}
