// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// CraftConfigBuilder is an alias of CraftConfig to build CraftConfig with builder-pattern.
type CraftConfigBuilder models.CraftConfig

// NewCraftConfigBuilder creates a new CraftConfigBuilder.
func NewCraftConfigBuilder() *CraftConfigBuilder {
	return &CraftConfigBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *CraftConfigBuilder) Copy() *CraftConfigBuilder {
	c := *b
	return &c
}

// Build returns built CraftConfig.
func (b *CraftConfigBuilder) Build() *models.CraftConfig {
	return (*models.CraftConfig)(b)
}

// SetCI sets CraftConfig's CI.
func (b *CraftConfigBuilder) SetCI(ci string) *CraftConfigBuilder {
	b.CI = ci
	return b
}

// SetCodeCov sets CraftConfig's CodeCov.
func (b *CraftConfigBuilder) SetCodeCov(codeCov bool) *CraftConfigBuilder {
	b.CodeCov = codeCov
	return b
}

// SetDescription sets CraftConfig's Description.
func (b *CraftConfigBuilder) SetDescription(description string) *CraftConfigBuilder {
	b.Description = &description
	return b
}

// SetDockerRegistry sets CraftConfig's DockerRegistry.
func (b *CraftConfigBuilder) SetDockerRegistry(dockerRegistry string) *CraftConfigBuilder {
	b.DockerRegistry = &dockerRegistry
	return b
}

// SetLicense sets CraftConfig's License.
func (b *CraftConfigBuilder) SetLicense(license string) *CraftConfigBuilder {
	b.License = &license
	return b
}

// SetMaintainers sets CraftConfig's Maintainers.
func (b *CraftConfigBuilder) SetMaintainers(maintainers ...models.Maintainer) *CraftConfigBuilder {
	b.Maintainers = append(b.Maintainers, maintainers...)
	return b
}

// SetNoAPI sets CraftConfig's NoAPI.
func (b *CraftConfigBuilder) SetNoAPI(noAPI bool) *CraftConfigBuilder {
	b.NoAPI = noAPI
	return b
}

// SetNoChart sets CraftConfig's NoChart.
func (b *CraftConfigBuilder) SetNoChart(noChart bool) *CraftConfigBuilder {
	b.NoChart = noChart
	return b
}

// SetNoDockerfile sets CraftConfig's NoDockerfile.
func (b *CraftConfigBuilder) SetNoDockerfile(noDockerfile bool) *CraftConfigBuilder {
	b.NoDockerfile = noDockerfile
	return b
}

// SetNoGoreleaser sets CraftConfig's NoGoreleaser.
func (b *CraftConfigBuilder) SetNoGoreleaser(noGoreleaser bool) *CraftConfigBuilder {
	b.NoGoreleaser = noGoreleaser
	return b
}

// SetNoMakefile sets CraftConfig's NoMakefile.
func (b *CraftConfigBuilder) SetNoMakefile(noMakefile bool) *CraftConfigBuilder {
	b.NoMakefile = noMakefile
	return b
}

// SetOpenAPIVersion sets CraftConfig's OpenAPIVersion.
func (b *CraftConfigBuilder) SetOpenAPIVersion(openAPIVersion string) *CraftConfigBuilder {
	b.OpenAPIVersion = openAPIVersion
	return b
}

// SetPort sets CraftConfig's Port.
func (b *CraftConfigBuilder) SetPort(port uint16) *CraftConfigBuilder {
	b.Port = &port
	return b
}

// SetSonar sets CraftConfig's Sonar.
func (b *CraftConfigBuilder) SetSonar(sonar bool) *CraftConfigBuilder {
	b.Sonar = sonar
	return b
}
