// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// DockerBuilder represents Docker's builder.
type DockerBuilder struct {
	build models.Docker
}

// NewDockerBuilder creates a new DockerBuilder.
func NewDockerBuilder() *DockerBuilder {
	return &DockerBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *DockerBuilder) Copy() *DockerBuilder {
	return &DockerBuilder{b.build}
}

// Build returns built Docker.
func (b *DockerBuilder) Build() *models.Docker {
	result := b.build
	return &result
}

// Port sets Docker's Port.
func (b *DockerBuilder) Port(port uint16) *DockerBuilder {
	b.build.Port = &port
	return b
}

// Registry sets Docker's Registry.
func (b *DockerBuilder) Registry(registry string) *DockerBuilder {
	b.build.Registry = &registry
	return b
}
