// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// DockerBuilder is an alias of Docker to build Docker with builder-pattern.
type DockerBuilder models.Docker

// NewDockerBuilder creates a new DockerBuilder.
func NewDockerBuilder() *DockerBuilder {
	return &DockerBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *DockerBuilder) Copy() *DockerBuilder {
	c := *b
	return &c
}

// Build returns built Docker.
func (b *DockerBuilder) Build() *models.Docker {
	c := (models.Docker)(*b)
	return &c
}

// SetPort sets Docker's Port.
func (b *DockerBuilder) SetPort(port uint16) *DockerBuilder {
	b.Port = &port
	return b
}

// SetRegistry sets Docker's Registry.
func (b *DockerBuilder) SetRegistry(registry string) *DockerBuilder {
	b.Registry = &registry
	return b
}
