// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// GenerateOptionsBuilder is an alias of GenerateOptions to build GenerateOptions with builder-pattern.
type GenerateOptionsBuilder models.GenerateOptions

// NewGenerateOptionsBuilder creates a new GenerateOptionsBuilder.
func NewGenerateOptionsBuilder() *GenerateOptionsBuilder {
	return &GenerateOptionsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *GenerateOptionsBuilder) Copy() *GenerateOptionsBuilder {
	c := *b
	return &c
}

// Build returns built GenerateOptions.
func (b *GenerateOptionsBuilder) Build() *models.GenerateOptions {
	return (*models.GenerateOptions)(b)
}

// SetDestinationDir sets GenerateOptions's DestinationDir.
func (b *GenerateOptionsBuilder) SetDestinationDir(destinationDir string) *GenerateOptionsBuilder {
	b.DestinationDir = destinationDir
	return b
}

// SetEndDelim sets GenerateOptions's EndDelim.
func (b *GenerateOptionsBuilder) SetEndDelim(endDelim string) *GenerateOptionsBuilder {
	b.EndDelim = endDelim
	return b
}

// SetForce sets GenerateOptions's Force.
func (b *GenerateOptionsBuilder) SetForce(force ...string) *GenerateOptionsBuilder {
	b.Force = append(b.Force, force...)
	return b
}

// SetForceAll sets GenerateOptions's ForceAll.
func (b *GenerateOptionsBuilder) SetForceAll(forceAll bool) *GenerateOptionsBuilder {
	b.ForceAll = forceAll
	return b
}

// SetStartDelim sets GenerateOptions's StartDelim.
func (b *GenerateOptionsBuilder) SetStartDelim(startDelim string) *GenerateOptionsBuilder {
	b.StartDelim = startDelim
	return b
}

// SetTemplatesDir sets GenerateOptions's TemplatesDir.
func (b *GenerateOptionsBuilder) SetTemplatesDir(templatesDir string) *GenerateOptionsBuilder {
	b.TemplatesDir = templatesDir
	return b
}
