// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// GenerateConfigBuilder represents GenerateConfig's builder.
type GenerateConfigBuilder struct {
	build models.GenerateConfig
}

// NewGenerateConfigBuilder creates a new GenerateConfigBuilder.
func NewGenerateConfigBuilder() *GenerateConfigBuilder {
	return &GenerateConfigBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *GenerateConfigBuilder) Copy() *GenerateConfigBuilder {
	return &GenerateConfigBuilder{b.build}
}

// Build returns built GenerateConfig.
func (b *GenerateConfigBuilder) Build() *models.GenerateConfig {
	result := b.build
	return &result
}

// SetBinaries sets GenerateConfig's Binaries.
func (b *GenerateConfigBuilder) SetBinaries(binaries uint8) *GenerateConfigBuilder {
	b.build.Binaries = binaries
	return b
}

// SetClis sets GenerateConfig's Clis.
func (b *GenerateConfigBuilder) SetClis(clis map[string]struct{}) *GenerateConfigBuilder {
	b.build.Clis = clis
	return b
}

// SetCraftConfig sets GenerateConfig's CraftConfig.
func (b *GenerateConfigBuilder) SetCraftConfig(craftConfig models.CraftConfig) *GenerateConfigBuilder {
	b.build.CraftConfig = craftConfig
	return b
}

// SetCrons sets GenerateConfig's Crons.
func (b *GenerateConfigBuilder) SetCrons(crons map[string]struct{}) *GenerateConfigBuilder {
	b.build.Crons = crons
	return b
}

// SetJobs sets GenerateConfig's Jobs.
func (b *GenerateConfigBuilder) SetJobs(jobs map[string]struct{}) *GenerateConfigBuilder {
	b.build.Jobs = jobs
	return b
}

// SetLanguages sets GenerateConfig's Languages.
func (b *GenerateConfigBuilder) SetLanguages(languages ...string) *GenerateConfigBuilder {
	b.build.Languages = append(b.build.Languages, languages...)
	return b
}

// SetLangVersion sets GenerateConfig's LangVersion.
func (b *GenerateConfigBuilder) SetLangVersion(langVersion string) *GenerateConfigBuilder {
	b.build.LangVersion = langVersion
	return b
}

// SetOptions sets GenerateConfig's Options.
func (b *GenerateConfigBuilder) SetOptions(options models.GenerateOptions) *GenerateConfigBuilder {
	b.build.Options = options
	return b
}

// SetProjectHost sets GenerateConfig's ProjectHost.
func (b *GenerateConfigBuilder) SetProjectHost(projectHost string) *GenerateConfigBuilder {
	b.build.ProjectHost = projectHost
	return b
}

// SetProjectName sets GenerateConfig's ProjectName.
func (b *GenerateConfigBuilder) SetProjectName(projectName string) *GenerateConfigBuilder {
	b.build.ProjectName = projectName
	return b
}

// SetProjectPath sets GenerateConfig's ProjectPath.
func (b *GenerateConfigBuilder) SetProjectPath(projectPath string) *GenerateConfigBuilder {
	b.build.ProjectPath = projectPath
	return b
}

// SetWorkers sets GenerateConfig's Workers.
func (b *GenerateConfigBuilder) SetWorkers(workers map[string]struct{}) *GenerateConfigBuilder {
	b.build.Workers = workers
	return b
}
