// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// GenerateOptionsBuilder represents GenerateOptions's builder.
type GenerateOptionsBuilder struct {
	build models.GenerateOptions
}

// NewGenerateOptionsBuilder creates a new GenerateOptionsBuilder.
func NewGenerateOptionsBuilder() *GenerateOptionsBuilder {
	return &GenerateOptionsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *GenerateOptionsBuilder) Copy() *GenerateOptionsBuilder {
	return &GenerateOptionsBuilder{b.build}
}

// Build returns built GenerateOptions.
func (b *GenerateOptionsBuilder) Build() *models.GenerateOptions {
	result := b.build
	return &result
}

// SetDestinationDir sets GenerateOptions's DestinationDir.
func (b *GenerateOptionsBuilder) SetDestinationDir(destinationDir string) *GenerateOptionsBuilder {
	b.build.DestinationDir = destinationDir
	return b
}

// SetEndDelim sets GenerateOptions's EndDelim.
func (b *GenerateOptionsBuilder) SetEndDelim(endDelim string) *GenerateOptionsBuilder {
	b.build.EndDelim = endDelim
	return b
}

// SetForce sets GenerateOptions's Force.
func (b *GenerateOptionsBuilder) SetForce(force ...string) *GenerateOptionsBuilder {
	b.build.Force = append(b.build.Force, force...)
	return b
}

// SetForceAll sets GenerateOptions's ForceAll.
func (b *GenerateOptionsBuilder) SetForceAll(forceAll bool) *GenerateOptionsBuilder {
	b.build.ForceAll = forceAll
	return b
}

// SetStartDelim sets GenerateOptions's StartDelim.
func (b *GenerateOptionsBuilder) SetStartDelim(startDelim string) *GenerateOptionsBuilder {
	b.build.StartDelim = startDelim
	return b
}

// SetTemplatesDir sets GenerateOptions's TemplatesDir.
func (b *GenerateOptionsBuilder) SetTemplatesDir(templatesDir string) *GenerateOptionsBuilder {
	b.build.TemplatesDir = templatesDir
	return b
}
