// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// MaintainerBuilder represents Maintainer's builder.
type MaintainerBuilder struct {
	build models.Maintainer
}

// NewMaintainerBuilder creates a new MaintainerBuilder.
func NewMaintainerBuilder() *MaintainerBuilder {
	return &MaintainerBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *MaintainerBuilder) Copy() *MaintainerBuilder {
	return &MaintainerBuilder{b.build}
}

// Build returns built Maintainer.
func (b *MaintainerBuilder) Build() *models.Maintainer {
	result := b.build
	return &result
}

// Email sets Maintainer's Email.
func (b *MaintainerBuilder) Email(email string) *MaintainerBuilder {
	b.build.Email = &email
	return b
}

// Name sets Maintainer's Name.
func (b *MaintainerBuilder) Name(name string) *MaintainerBuilder {
	b.build.Name = name
	return b
}

// URL sets Maintainer's URL.
func (b *MaintainerBuilder) URL(url string) *MaintainerBuilder {
	b.build.URL = &url
	return b
}
