// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// MaintainerBuilder is an alias of Maintainer to build Maintainer with builder-pattern.
type MaintainerBuilder models.Maintainer

// NewMaintainerBuilder creates a new MaintainerBuilder.
func NewMaintainerBuilder() *MaintainerBuilder {
	return &MaintainerBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *MaintainerBuilder) Copy() *MaintainerBuilder {
	c := *b
	return &c
}

// Build returns built Maintainer.
func (b *MaintainerBuilder) Build() *models.Maintainer {
	c := (models.Maintainer)(*b)
	return &c
}

// SetEmail sets Maintainer's Email.
func (b *MaintainerBuilder) SetEmail(email string) *MaintainerBuilder {
	b.Email = &email
	return b
}

// SetName sets Maintainer's Name.
func (b *MaintainerBuilder) SetName(name string) *MaintainerBuilder {
	b.Name = name
	return b
}

// SetURL sets Maintainer's URL.
func (b *MaintainerBuilder) SetURL(url string) *MaintainerBuilder {
	b.URL = &url
	return b
}
