// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/models"
)

// ReleaseBuilder represents Release's builder.
type ReleaseBuilder struct {
	build models.Release
}

// NewReleaseBuilder creates a new ReleaseBuilder.
func NewReleaseBuilder() *ReleaseBuilder {
	return &ReleaseBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *ReleaseBuilder) Copy() *ReleaseBuilder {
	return &ReleaseBuilder{b.build}
}

// Build returns built Release.
func (b *ReleaseBuilder) Build() *models.Release {
	result := b.build
	return &result
}

// Auto sets Release's Auto.
func (b *ReleaseBuilder) Auto(auto bool) *ReleaseBuilder {
	b.build.Auto = auto
	return b
}

// Backmerge sets Release's Backmerge.
func (b *ReleaseBuilder) Backmerge(backmerge bool) *ReleaseBuilder {
	b.build.Backmerge = backmerge
	return b
}

// Mode sets Release's Mode.
func (b *ReleaseBuilder) Mode(mode string) *ReleaseBuilder {
	b.build.Mode = mode
	return b
}
