package generate

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	"github.com/kilianpaquier/cli-sdk/pkg/cfs"
	"github.com/kilianpaquier/cli-sdk/pkg/clog"
	"github.com/kilianpaquier/craft/pkg/craft"
	"github.com/kilianpaquier/craft/pkg/templating"
)

var (
	errDelete = errors.New("file deletion")
	errExist  = errors.New("file already exists")
)

// generated is the string for generated files.
const generated = "Code generated by craft; DO NOT EDIT."

// IsGenerated returns truthy if input destination is a generated file.
func IsGenerated(dest string) bool {
	// retrieve file content, if there's an error, generation to make
	content, err := os.ReadFile(dest)
	if err != nil {
		return true
	}

	// special case (shouldn't happen) where the destination has been replaced with an empty file
	if len(content) == 0 {
		return true
	}
	lines := strings.Split(string(content), "\n")

	// check first line for generated regexp
	if len(lines) >= 1 && strings.Contains(lines[0], generated) {
		return true
	}

	// check second line for generated regexp
	if len(lines) >= 2 && strings.Contains(lines[1], generated) {
		return true
	}
	return false
}

// DefaultExec is a simplified function returning a basic Exec for an input template folder name.
func DefaultExec(name string) Exec {
	return func(_ context.Context, log clog.Logger, fsys cfs.FS, srcdir, destdir string, metadata Metadata, opts ExecOpts) error {
		return handleDir(log, fsys, srcdir, destdir, metadata, name, opts)
	}
}

// handleDir walks over input srcdir and apply template of every src entry into destdir.
func handleDir(log clog.Logger, fsys cfs.FS, srcdir, destdir string, data any, name string, opts ExecOpts) error { // nolint:revive
	// read source directory
	entries, err := fsys.ReadDir(srcdir)
	if err != nil {
		return fmt.Errorf("read directory: %w", err)
	}

	errs := make([]error, 0, len(entries))
	for _, entry := range entries {
		src := path.Join(srcdir, entry.Name())
		dest := filepath.Join(destdir, entry.Name())

		if entry.IsDir() {
			// apply generation at root if the folder name is the dir generate name
			if entry.Name() == name {
				errs = append(errs, handleDir(log, fsys, src, destdir, data, name, opts))
				continue
			}

			// apply templates on subdirs not being the reserved ones for languages
			if !strings.HasPrefix(entry.Name(), "lang_") {
				errs = append(errs, handleDir(log, fsys, src, dest, data, name, opts))
				continue
			}
			continue
		}

		// don't template files without .tmpl extension
		if !strings.HasSuffix(src, craft.TmplExtension) {
			continue
		}
		dest = strings.TrimSuffix(dest, craft.TmplExtension)

		if err := handleFile(fsys, src, dest, data, opts); err != nil {
			if errors.Is(err, errDelete) {
				log.Warnf("failed to delete '%s': %s", entry.Name(), err.Error())
				continue
			}
			if errors.Is(err, errExist) {
				log.Infof("not copying '%s' since it already exists", filepath.Base(dest))
				continue
			}
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// handleFile is a private function used to handle a specific file entry
// during iterative loops over folders and subfolders.
func handleFile(fsys cfs.FS, src, dest string, data any, opts ExecOpts) error {
	filename := filepath.Base(dest)

	// verify that file matches generation rules
	generate := opts.ForceAll || IsGenerated(dest) || slices.Contains(opts.Force, filename)
	singleGeneration := filename == craft.File && cfs.Exists(dest)
	if !generate || singleGeneration {
		return errExist
	}

	// check if filename matches an optional file
	for _, handler := range opts.FileHandlers {
		ok, apply := handler(src, dest, filename)
		if !ok {
			// don't do anything since the handler is not the right one for this file
			continue
		}
		if apply {
			// break loop since optional file was found
			break
		}

		// handle optional file deletion
		if err := os.RemoveAll(dest); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("remove file '%s': %w: %w", filename, errDelete, err)
		}
		return nil
	}

	tmpl, err := template.New(filepath.Base(src)).
		Funcs(sprig.FuncMap()).
		Funcs(templating.FuncMap()).
		Delims(opts.StartDelim, opts.EndDelim).
		ParseFS(fsys, src)
	if err != nil {
		return fmt.Errorf("parse template file: %w", err)
	}
	return templating.Execute(tmpl, data, dest)
}
