{{- define "golang" }}

{{- $specifics := get .Languages "go" }}

{{- $binaries := dict }}
{{- $_ := map $binaries .Clis .Crons .Jobs .Workers }}

{{- $maintainer := index .Maintainers 0 }}

#############################
#        STAGE BUILD        #
#############################
{{- if $specifics.Toolchain }}
FROM golang:{{ $specifics.Toolchain }} AS build
{{- else }}
FROM golang:{{ $specifics.Go }} AS build
{{- end }}

ARG CGO_ENABLED=0
ARG GIT_REF_NAME
ARG GIT_COMMIT
ARG VERSION=v0.0.0

WORKDIR /app

COPY . .

RUN go mod download{{ range $name, $config := $binaries }} && \
    CGO_ENABLED=$CGO_ENABLED go build \
        -ldflags "\
            -X '{{ $specifics.Module }}/internal/build.branch=$GIT_REF_NAME' \
            -X '{{ $specifics.Module }}/internal/build.commit=$GIT_COMMIT' \
            -X '{{ $specifics.Module }}/internal/build.date=$(TZ="UTC" date '+%Y-%m-%dT%TZ')' \
            -X '{{ $specifics.Module }}/internal/build.version=$VERSION' \
        " \
        -o {{ $name }} ./cmd/{{ $name }}
{{- end }}

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="{{ $maintainer.Name }}{{ if $maintainer.Email }} <{{ $maintainer.Email }}>{{ end }}"
LABEL org.opencontainers.image.vendor="{{ $maintainer.Name }}"

LABEL org.opencontainers.image.title="{{ .ProjectName }}"
{{- if .Description }}
LABEL org.opencontainers.image.description="{{ .Description }}"
{{- end }}
{{- if .License }}
LABEL org.opencontainers.image.licenses="{{ upper .License }}"
{{- end }}
LABEL org.opencontainers.image.url="{{ print .ProjectHost "/" .ProjectPath }}"
LABEL org.opencontainers.image.source="{{ print .ProjectHost "/" .ProjectPath }}"
LABEL org.opencontainers.image.documentation="{{ print .ProjectHost "/" .ProjectPath }}"

WORKDIR /app

COPY --from=build \
{{- range $name, $config := $binaries }}
    /app/{{ $name }} \
{{- end }}
    ./

{{- $entrypoint := "launcher.sh" }}

{{- if eq .Binaries 1 }}

{{- /* directly use the only binary */ -}}
{{- range $name, $config := $binaries }}
{{- $entrypoint = $name }}
{{- end }}

{{- end }}

{{- /* copy launcher if the entrypoint is the launcher */ -}}
{{- if eq $entrypoint "launcher.sh" }}
COPY launcher.sh launcher.sh
{{- end }}

EXPOSE {{ .CI.Docker.Port | default 3000 }}

ENTRYPOINT [ "/app/{{ $entrypoint }}" ]
{{- end }}
