# This file is safe to edit. Once it exists it will not be overwritten.

---
include:
  - .gitlab/workflows/version.yml
  - .gitlab/workflows/integration.yml

# secret variables
# (define the variables below in your GitLab group/project variables)
# GITLAB_TOKEN: A GitLab 'project access token' or 'personal access token' with `api`, `read_repository` and `write repository` scopes.
# SEMREL_GPG_SIGNKEY: Path to the GPG signkey exported with `gpg --armor --export-secret-key`.
# CI_REGISTRY_USER: The user with write access to ghcr.io to push docker images
# CI_REGISTRY_PASSWORD: The user password / token with write access to ghcr.io to push docker images
# RENOVATE_TOKEN: A GitLab access token to allow Renovate crawl your projects. [See doc](https://docs.renovatebot.com/modules/platform/gitlab/#authentication)
# GITHUB_COM_TOKEN: A GitHub access token to allow Renovate fetch changelogs. [See doc](https://docs.renovatebot.com/getting-started/running/#githubcom-token-for-changelogs)
# SONAR_TOKEN: SonarQube authentication token (depends on your authentication method)
# SONAR_LOGIN: SonarQube login (depends on your authentication method)
# SONAR_PASSWORD: SonarQube password (depends on your authentication method)

variables:
  PROD_REF: main
  REVIEW_REF: staging
  INTEG_REF: develop