# Code generated by craft; DO NOT EDIT.

.PHONY: build
build:
	@hugo --gc --minify --destination dist

.PHONY: serve
serve:
	@hugo server --disableFastRender

.PHONY: production
production:
	@netlify dev -c "make serve" \
		--target-port 1313 --port 8888
		--dir dist
		--framework hugo
		--context production