# Code generated by craft; DO NOT EDIT.

.PHONY: clean
clean:
	@git clean -dfX

.PHONY: build
build:
	@hugo --gc --minify --destination dist --logLevel debug

.PHONY: serve
serve:
	@hugo server --disableFastRender --destination dist --logLevel debug

.PHONY: production
production: build
	@python3 -m http.server --directory dist
