// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/craft/internal/generate/detectgen"
)

// GomodBuilder represents Gomod's builder.
type GomodBuilder struct {
	build detectgen.Gomod
}

// NewGomodBuilder creates a new GomodBuilder.
func NewGomodBuilder() *GomodBuilder {
	return &GomodBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *GomodBuilder) Copy() *GomodBuilder {
	return &GomodBuilder{b.build}
}

// Build returns built Gomod.
func (b *GomodBuilder) Build() *detectgen.Gomod {
	result := b.build
	return &result
}

// LangVersion sets Gomod's LangVersion.
func (b *GomodBuilder) LangVersion(langVersion string) *GomodBuilder {
	b.build.LangVersion = langVersion
	return b
}

// Platform sets Gomod's Platform.
func (b *GomodBuilder) Platform(platform string) *GomodBuilder {
	b.build.Platform = platform
	return b
}

// ProjectHost sets Gomod's ProjectHost.
func (b *GomodBuilder) ProjectHost(projectHost string) *GomodBuilder {
	b.build.ProjectHost = projectHost
	return b
}

// ProjectName sets Gomod's ProjectName.
func (b *GomodBuilder) ProjectName(projectName string) *GomodBuilder {
	b.build.ProjectName = projectName
	return b
}

// ProjectPath sets Gomod's ProjectPath.
func (b *GomodBuilder) ProjectPath(projectPath string) *GomodBuilder {
	b.build.ProjectPath = projectPath
	return b
}
