// Code generated by go-swagger; DO NOT EDIT.

package monitoring

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnsecuredPingParams creates a new UnsecuredPingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnsecuredPingParams() *UnsecuredPingParams {
	return &UnsecuredPingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnsecuredPingParamsWithTimeout creates a new UnsecuredPingParams object
// with the ability to set a timeout on a request.
func NewUnsecuredPingParamsWithTimeout(timeout time.Duration) *UnsecuredPingParams {
	return &UnsecuredPingParams{
		timeout: timeout,
	}
}

// NewUnsecuredPingParamsWithContext creates a new UnsecuredPingParams object
// with the ability to set a context for a request.
func NewUnsecuredPingParamsWithContext(ctx context.Context) *UnsecuredPingParams {
	return &UnsecuredPingParams{
		Context: ctx,
	}
}

// NewUnsecuredPingParamsWithHTTPClient creates a new UnsecuredPingParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnsecuredPingParamsWithHTTPClient(client *http.Client) *UnsecuredPingParams {
	return &UnsecuredPingParams{
		HTTPClient: client,
	}
}

/*
UnsecuredPingParams contains all the parameters to send to the API endpoint

	for the unsecured ping operation.

	Typically these are written to a http.Request.
*/
type UnsecuredPingParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unsecured ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnsecuredPingParams) WithDefaults() *UnsecuredPingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unsecured ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnsecuredPingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unsecured ping params
func (o *UnsecuredPingParams) WithTimeout(timeout time.Duration) *UnsecuredPingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unsecured ping params
func (o *UnsecuredPingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unsecured ping params
func (o *UnsecuredPingParams) WithContext(ctx context.Context) *UnsecuredPingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unsecured ping params
func (o *UnsecuredPingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unsecured ping params
func (o *UnsecuredPingParams) WithHTTPClient(client *http.Client) *UnsecuredPingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unsecured ping params
func (o *UnsecuredPingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UnsecuredPingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
