# Code generated by craft; DO NOT EDIT.

.PHONY: build
build:
	@hugo --gc --minify --destination dist

.PHONY: serve
serve:
	@hugo server --disableFastRender

.PHONY: production
production: build
	@python3 -m http.server --directory dist