# Code generated by craft; DO NOT EDIT.

GOCI_LINT_PATH  ?= .golangci.yml
VERSION         ?= v0.0.0

.PHONY: reports
reports:
	@mkdir -p reports/

.PHONY: lint
lint: reports
	@golangci-lint run -c ${GOCI_LINT_PATH} --timeout 240s --allow-parallel-runners \
		--output.checkstyle.path "reports/go-ci-lint.checkstyle.xml" \
		--output.text.path stdout $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix: reports
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1 -timeout=15s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=15s

.PHONY: test-cover
test-cover: reports
	@go test ./... -v -coverpkg="./..." -covermode="count" -coverprofile="reports/go-coverage.native.out" -timeout=15s | tee "reports/tests.log"
	@go run github.com/jstemmer/go-junit-report/v2@latest -in "reports/tests.log" -out "reports/go-test.xunit.xml"
	@go tool test2json < "reports/tests.log" > "reports/go-test.native.json"

.PHONY: buildall
buildall: build-cron-name build-job-name build-worker-name

.PHONY: cron-name job-name worker-name
build-%:
	@CGO_ENABLED=0 go build \
		-ldflags "\
			-X 'gitlab.com/kilianpaquier/craft/internal/build.branch=$(shell git rev-parse --abbrev-ref HEAD)' \
			-X 'gitlab.com/kilianpaquier/craft/internal/build.commit=$(shell git rev-parse HEAD)' \
			-X 'gitlab.com/kilianpaquier/craft/internal/build.date=$(shell TZ="UTC" date '+%Y-%m-%dT%TZ')' \
			-X 'gitlab.com/kilianpaquier/craft/internal/build.version=${VERSION}' \
		" \
		-o $* ./cmd/$*

.PHONY: cron-name job-name worker-name
local-%:
	@go run ./cmd/$*

.PHONY: docker
docker:
	@docker build . \
		-f Dockerfile \
		-t craft:${VERSION} \
		--build-arg GIT_REF_NAME=$(shell git rev-parse --abbrev-ref HEAD) \
		--build-arg GIT_COMMIT=$(shell git rev-parse HEAD) \
		--build-arg VERSION=${VERSION}
