// Code generated by go-swagger; DO NOT EDIT.

// Package restapi golang-api
//
//	API craft example
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.1.0
//	License: mit
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
