// Code generated by go-swagger; DO NOT EDIT.

package test_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kilianpaquier/craft/models"
)

// TestTagNoContentCode is the HTTP code returned for type TestTagNoContent
const TestTagNoContentCode int = 204

/*
TestTagNoContent success response test tag result

swagger:response testTagNoContent
*/
type TestTagNoContent struct {
}

// NewTestTagNoContent creates TestTagNoContent with default headers values
func NewTestTagNoContent() *TestTagNoContent {

	return &TestTagNoContent{}
}

// WriteResponse to the client
func (o *TestTagNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
TestTagDefault default error response

swagger:response testTagDefault
*/
type TestTagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTestTagDefault creates TestTagDefault with default headers values
func NewTestTagDefault(code int) *TestTagDefault {
	if code <= 0 {
		code = 500
	}

	return &TestTagDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the test tag default response
func (o *TestTagDefault) WithStatusCode(code int) *TestTagDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the test tag default response
func (o *TestTagDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the test tag default response
func (o *TestTagDefault) WithPayload(payload *models.Error) *TestTagDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the test tag default response
func (o *TestTagDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TestTagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
