// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"net/http"
	"sync"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	log "github.com/sirupsen/logrus"

	internal_api "github.com/kilianpaquier/craft/examples/openapi_v2/internal/api"
	monitoring_api "github.com/kilianpaquier/craft/examples/openapi_v2/internal/api/monitoring"
	"github.com/kilianpaquier/craft/examples/openapi_v2/restapi/operations"
	"github.com/kilianpaquier/craft/examples/openapi_v2/restapi/operations/monitoring"
)

func configureFlags(api *operations.OpenapiV2API) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.OpenapiV2API) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	api.Logger = log.Infof

	api.UseSwaggerUI()
	// To continue using redoc as your UI, uncomment the following line
	// api.UseRedoc()

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.MonitoringUnsecuredPingHandler = monitoring.UnsecuredPingHandlerFunc(func(params monitoring.UnsecuredPingParams) middleware.Responder {
		return monitoring_api.UnsecuredPing(params)
	})

	api.PreServerShutdown = internal_api.PreServerShutdown
	api.ServerShutdown = internal_api.ServerShutdown

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

var startup sync.Once

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix".
func configureServer(s *http.Server, scheme, addr string) {
	startup.Do(internal_api.ServerStartup)
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation.
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics.
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
