// Code generated by go-swagger; DO NOT EDIT.

// Package restapi openapi_v2
//
//	Golang's craft openapi v2 example
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
