// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"context"

	"github.com/caarlos0/env/v10"
	"github.com/go-openapi/loads"
	log "github.com/sirupsen/logrus"

	"github.com/kilianpaquier/craft/examples/golang-api/restapi"
	"github.com/kilianpaquier/craft/examples/golang-api/restapi/operations"
)

type config struct {
	Port uint16 `env:"BINARY_PORT" envDefault:"3000"`
	Host string `env:"BINARY_HOST" envDefault:"0.0.0.0"`
}

func main() {
	ctx := context.Background()
	log := log.WithContext(ctx)

	var c config
	if err := env.Parse(&c); err != nil {
		log.WithError(err).Fatal("failed to load configuration")
	}

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.WithError(err).Fatal("failed to load embedded swagger")
	}

	api := operations.NewGolangAPIAPI(swaggerSpec)
	server := restapi.NewServer(api)

	server.Host = c.Host
	server.Port = int(c.Port)

	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.WithError(err).Fatal("failed to run server")
	}
}
