# Code generated by craft; DO NOT EDIT.

VERSION         ?= v0.0.0
GOCI_LINT_PATH  ?= .golangci.yml

.PHONY: reports
reports:
	@mkdir -p reports/

.PHONY: lint
lint: reports
	@golangci-lint run -c ${GOCI_LINT_PATH} --timeout 240s --fast --sort-results \
		--out-format checkstyle:reports/go-ci-lint.checkstyle.xml,colored-line-number $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix: reports
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1 -timeout=15s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=15s

.PHONY: test-cover
test-cover: reports
	@go test ./... -coverpkg="./..." -covermode="count" -coverprofile="reports/go-coverage.native.out" -timeout=15s

.PHONY: buildall
buildall: build-craft

.PHONY: craft
build-%:
	@[ -f "cmd/$*/main.go" ] || (echo "cmd/$*/main.go does not exist" && exit 1)
	@CGO_ENABLED=0 go build \
		-ldflags "\
			-X 'github.com/kilianpaquier/craft/internal/build.branch=$(shell git rev-parse --abbrev-ref HEAD)' \
			-X 'github.com/kilianpaquier/craft/internal/build.commit=$(shell git rev-parse HEAD)' \
			-X 'github.com/kilianpaquier/craft/internal/build.date=$(shell TZ="UTC" date '+%Y-%m-%dT%TZ')' \
			-X 'github.com/kilianpaquier/craft/internal/build.version=${VERSION}' \
		" \
		-o $* cmd/$*/main.go

.PHONY: craft
local-%:
	@[ -f "cmd/$*/main.go" ] || (echo "cmd/$*/main.go does not exist" && exit 1)
	@go run cmd/$*/main.go