layout:
  application:
    - name: configure
      source: asset:serverConfigureapi
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "configure_{{ .Name }}.go"
    - name: main
      source: asset:serverMain
      target: "{{ joinFilePath .Target \"cmd\" (dasherize (pascalize .Name)) }}-api"
      file_name: "main.go"
    - name: embedded_spec
      source: asset:swaggerJsonEmbed
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "embedded_spec.go"
    - name: server
      source: asset:serverServer
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "server.go"
    - name: builder
      source: asset:serverBuilder
      target: "{{ joinFilePath .Target .ServerPackage .Package }}"
      file_name: "{{ snakize (pascalize .Name) }}_api.go"
    - name: doc
      source: asset:serverDoc
      target: "{{ joinFilePath .Target .ServerPackage }}"
      file_name: "doc.go"
    # custom implementation with simple generation outside of generated package files
    - name: custom_authentication
      source: custom/authentication.gotmpl
      target: "{{ joinFilePath .Target \"internal\" \"api\" }}"
      file_name: "authentication.go"
      skip_exists: true
    # custom implementation with simple generation outside of generated package files
    - name: custom_server
      source: custom/server.gotmpl
      target: "{{ joinFilePath .Target \"internal\" \"api\" }}"
      file_name: "server.go"
      skip_exists: true
  models:
    - name: definition
      source: asset:model
      target: "{{ joinFilePath .Target .ModelPackage }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
  operations:
    - name: parameters
      source: asset:serverParameter
      target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}{{ else }}{{ joinFilePath .Target .ServerPackage .Package  }}{{ end }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_parameters.go"
    - name: responses
      source: asset:serverResponses
      target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}{{ else }}{{ joinFilePath .Target .ServerPackage .Package  }}{{ end }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_responses.go"
    - name: handler
      source: asset:serverOperation
      target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Target .ServerPackage .APIPackage .Package  }}{{ else }}{{ joinFilePath .Target .ServerPackage .Package  }}{{ end }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
    # custom implementation with simple generation outside of generated package files
    - name: custom_implementation
      source: custom/operation.gotmpl
      target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Target \"internal\" \"api\" .Package  }}{{ else }}{{ joinFilePath .Target \"internal\" \"api\" }}{{ end }}"
      file_name: "{{ (snakize (pascalize .Name)) }}.go"
      skip_exists: true
    # custom implementation with simple generation outside of generated package files
    - name: custom_implementation_test
      source: custom/operation_test.gotmpl
      target: "{{ if gt (len .Tags) 0 }}{{ joinFilePath .Target \"internal\" \"api\" .Package  }}{{ else }}{{ joinFilePath .Target \"internal\" \"api\" }}{{ end }}"
      file_name: "{{ (snakize (pascalize .Name)) }}_test.go"
      skip_exists: true
  operation_groups: